on:
  workflow_run:
    workflows: [Build on Push to Main]
    types:
      - completed
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'git@github.com:famsy-co/clinic-frontend.git'
          destination_repo: 'git@github.com:sina-salahshour/clinic-frontend.git'
          source_branch: 'main'
          destination_branch: 'main'
          ssh_private_key: ${{ secrets.SSH_KEY }}
